### ISSUE TITLE
Deleting an already existing block and then undoing the change shows ID:  Value has to be unique

### ISSUE THREAD

**Issue by JohannesPertl** [formfcw/directus-extension-flexible-editor#29] opened 2023-12-22 15:19 UTC
**Describe the bug**
When deleting a block that was already saved before inside the editor and then undoing the change, the error `ID: Value has to be unique` is shown. Probably, because it tries to create a new block instead of referencing the old one.

**To Reproduce**
1. Create a block in the flexible editor, save the collection item. 
2. Open the collection item, delete the block and undo the change. 
3. Try to save

**Flexible Editor Version:**
[e.g. 1.1.7]

**Directus Version:**
[e.g. 10.8.3]

**Comment by formfcw** [comment] 2024-02-08 10:47
Does the bug still occur on your system? I can't reproduce it. Can you give me more information about what kind of block it is?

**Comment by JohannesPertl** [comment] 2024-04-07 18:06
It always occurs with any custom block, even on the latest version. Here's a video: 

https://github.com/formfcw/directus-extension-flexible-editor/assets/45853628/db816a7d-1384-4dad-a9c7-be0ae3fb3820

**Comment by formfcw** [comment] 2024-04-11 08:45
Can you please provide more information on how to reproduce the bug? This could be either your schema created by the directus cli or a step-by-step guide on how to rebuild your collections and blocks.

Maybe you can also share your directus env vars (without sensitive data)?

**Comment by JohannesPertl** [comment] 2024-04-11 13:04
@formfcw I created the simplest representation of a project where the bug occurs, the schema is included: https://github.com/JohannesPertl/directus_bug_test/tree/main

**Comment by formfcw** [comment] 2024-04-12 11:38
@JohannesPertl 🙏  Thanks for sharing the repo. I can now reproduce the bug. It seems to be a tricky one.

As a not-so-user-friendly workaround: If you manually refresh the page after creating an item, the bug does not appear.

**Comment by formfcw** [comment] 2024-04-12 15:15
Will be fixed in `v1.4.2`.
Stay tuned!

**Closed by formfcw** 2024-04-12 15:15 UTC
Labels: bug
